import{a as q,S as I,i as l}from"./assets/vendor-BMSPLjta.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const T="46807099-cbb80e6feaa2f2d0498acb57e",x="https://pixabay.com/api/";let u=1,y="";async function w(n){y=n;const r=`${x}?key=${T}&q=${encodeURIComponent(y)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${u}`;try{const t=await q.get(r);return u++,{images:t.data.hits,totalHits:t.data.totalHits}}catch(t){throw console.error("Error fetching images:",t),t}}function M(){u=1}function p(){return u}const L=document.querySelector(".gallery");function O(){L.innerHTML=""}function b(n){const r=n.map(({webformatURL:t,largeImageURL:s,tags:e,likes:o,views:a,comments:P,downloads:$})=>`
      <a href="${s}" class="gallery__item">
        <img class="gallery-link" src="${t}" alt="${e}" loading="lazy" />
        <div class="info">
          <p class="text-item"><b>Likes:</b> ${o}</p>
          <p class="text-item"><b>Views:</b> ${a}</p>
          <p class="text-item"><b>Comments:</b> ${P}</p>
          <p class="text-item"><b>Downloads:</b> ${$}</p>
        </div>
      </a>
    `).join("");L.insertAdjacentHTML("beforeend",r),new I(".gallery a").refresh()}const _=document.querySelector("#search-form"),E=document.querySelector(".loader"),h=document.querySelector(".load-more");let m="",i=!1,c=0,f=null;function S(){E.classList.remove("hidden")}function d(){E.classList.add("hidden")}function v(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}async function H(){if(!i){i=!0,S();try{const{images:n,totalHits:r}=await w(m);d(),i=!1,r!==void 0&&(c=r),n.length===0||p()*15>=c?(g(),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):(b(n),p()*15<c?v():g())}catch{d(),i=!1,l.error({title:"Error",message:"Something went wrong. Please try again later!"})}}}function A(){f||(f=setTimeout(()=>{f=null,window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-100&&!i&&H()},2e3))}_.addEventListener("submit",async n=>{n.preventDefault();const r=n.currentTarget.elements.query.value.trim();if(!r){l.error({title:"Error",message:"Please enter a search term!"});return}m=r,O(),M(),g(),S();try{const{images:t,totalHits:s}=await w(m);d(),s!==void 0&&(c=s),t.length===0?l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(b(t),t.length<c&&v())}catch{d(),l.error({title:"Error",message:"Something went wrong. Please try again later!"})}});h.addEventListener("click",H);window.addEventListener("scroll",A);
//# sourceMappingURL=index.js.map
